version: '1.0.0'
services:
  landing:
    image: 283744739160.dkr.ecr.eu-central-1.amazonaws.com/inthee/landing-page-frontend
    ports:
      - 80:2222
    restart: always
    build: /landing
    depends_on:
      - landing-backend
  landing-backend:
    image: 283744739160.dkr.ecr.eu-central-1.amazonaws.com/inthee/landing-page-backend
    ports:
      - 3000:3000
    restart: always
    build: /landing-api
